--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-07-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AFICIONADOS_CONFLICTIVOS
--------------------------------------------------------

  CREATE TABLE "HR"."AFICIONADOS_CONFLICTIVOS" 
   (	"ID_AFICIONADOSCONF" NUMBER, 
	"ID_AFICIÓN" NUMBER, 
	"NOMBRE_AFICIONADO" VARCHAR2(50 BYTE), 
	"DNI" VARCHAR2(9 BYTE), 
	"FECHA_NACIMIENTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HR"."AFICIONADOS_CONFLICTIVOS"."ID_AFICIONADOSCONF" IS 'Clave Primaria';
   COMMENT ON COLUMN "HR"."AFICIONADOS_CONFLICTIVOS"."ID_AFICIÓN" IS 'Clave ajena';
   COMMENT ON COLUMN "HR"."AFICIONADOS_CONFLICTIVOS"."NOMBRE_AFICIONADO" IS 'Nombre aficionados conflictivos';
   COMMENT ON COLUMN "HR"."AFICIONADOS_CONFLICTIVOS"."DNI" IS 'D.N.I. aficionado conflictivo';
   COMMENT ON COLUMN "HR"."AFICIONADOS_CONFLICTIVOS"."FECHA_NACIMIENTO" IS 'Fecha nacimiento aficionado conflictivo';
--------------------------------------------------------
--  DDL for Index AFICIONADOS_CONFLICTIVOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."AFICIONADOS_CONFLICTIVOS_PK" ON "HR"."AFICIONADOS_CONFLICTIVOS" ("ID_AFICIONADOSCONF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AFICIONADOS_CONFLICTIVOS
--------------------------------------------------------

  ALTER TABLE "HR"."AFICIONADOS_CONFLICTIVOS" ADD CONSTRAINT "AFICIONADOS_CONFLICTIVOS_PK" PRIMARY KEY ("ID_AFICIONADOSCONF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."AFICIONADOS_CONFLICTIVOS" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "HR"."AFICIONADOS_CONFLICTIVOS" MODIFY ("ID_AFICIÓN" NOT NULL ENABLE);
  ALTER TABLE "HR"."AFICIONADOS_CONFLICTIVOS" MODIFY ("ID_AFICIONADOSCONF" NOT NULL ENABLE);
