--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View VISTA_FUTBOL
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "LALIGA"."VISTA_FUTBOL" ("NOMBRE_JUGADOR", "APELLIDOS", "SALARIO", "NOMBRE_EQUIPO") AS 
  SELECT 
    J.NOMBRE_JUGADOR,
    J.APELLIDOS,
    J.SALARIO,
    E.NOMBRE_EQUIPO
FROM 
    JUGADORES J,
    EQUIPO E
WHERE
    J.EQUIPO_ID = E.EQUIPO_ID
    AND J.SALARIO > 2000;
--------------------------------------------------------
--  DDL for Table AFICIÓN
--------------------------------------------------------

  CREATE TABLE "LALIGA"."AFICIÓN" 
   (	"AFICIÓN_ID" NUMBER, 
	"NOMBRE_GUERRA" VARCHAR2(50 BYTE), 
	"EQUIPO_ID" NUMBER, 
	"ABONADOS" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "LALIGA"."AFICIÓN"."AFICIÓN_ID" IS 'Clave Primaria';
   COMMENT ON COLUMN "LALIGA"."AFICIÓN"."NOMBRE_GUERRA" IS 'Nombre de guerra de la afición';
   COMMENT ON COLUMN "LALIGA"."AFICIÓN"."EQUIPO_ID" IS 'Clave Ajena';
   COMMENT ON COLUMN "LALIGA"."AFICIÓN"."ABONADOS" IS 'Número de abonados';
--------------------------------------------------------
--  DDL for Table AFICIONADOS_CONFLICTIVOS
--------------------------------------------------------

  CREATE TABLE "LALIGA"."AFICIONADOS_CONFLICTIVOS" 
   (	"ID_AFICIONADOSCONF" NUMBER, 
	"ID_AFICIÓN" NUMBER, 
	"NOMBRE_AFICIONADO" VARCHAR2(50 BYTE), 
	"DNI" VARCHAR2(9 BYTE), 
	"FECHA_NACIMIENTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "LALIGA"."AFICIONADOS_CONFLICTIVOS"."ID_AFICIONADOSCONF" IS 'Clave Primaria';
   COMMENT ON COLUMN "LALIGA"."AFICIONADOS_CONFLICTIVOS"."ID_AFICIÓN" IS 'Clave ajena';
   COMMENT ON COLUMN "LALIGA"."AFICIONADOS_CONFLICTIVOS"."NOMBRE_AFICIONADO" IS 'Nombre aficionados conflictivos';
   COMMENT ON COLUMN "LALIGA"."AFICIONADOS_CONFLICTIVOS"."DNI" IS 'D.N.I. aficionado conflictivo';
   COMMENT ON COLUMN "LALIGA"."AFICIONADOS_CONFLICTIVOS"."FECHA_NACIMIENTO" IS 'Fecha nacimiento aficionado conflictivo';
--------------------------------------------------------
--  DDL for Table CÁNTICOS
--------------------------------------------------------

  CREATE TABLE "LALIGA"."CÁNTICOS" 
   (	"CÁNTICO_ID" NUMBER, 
	"AFICIÓN_ID" NUMBER, 
	"TÍTULO_CANCIÓN" VARCHAR2(20 BYTE), 
	"FECHA_COMPOSICIÓN" DATE, 
	"LETRA_CANCIÓN" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "LALIGA"."CÁNTICOS"."CÁNTICO_ID" IS 'Clave Primaria';
   COMMENT ON COLUMN "LALIGA"."CÁNTICOS"."AFICIÓN_ID" IS 'Clave Ajena';
   COMMENT ON COLUMN "LALIGA"."CÁNTICOS"."TÍTULO_CANCIÓN" IS 'Título del cántico';
   COMMENT ON COLUMN "LALIGA"."CÁNTICOS"."FECHA_COMPOSICIÓN" IS 'Fecha de la composición del cántico';
   COMMENT ON COLUMN "LALIGA"."CÁNTICOS"."LETRA_CANCIÓN" IS 'Letra de la canción';
--------------------------------------------------------
--  DDL for Table EQUIPO
--------------------------------------------------------

  CREATE TABLE "LALIGA"."EQUIPO" 
   (	"EQUIPO_ID" NUMBER, 
	"NOMBRE_EQUIPO" VARCHAR2(40 BYTE), 
	"FECHA_FUNDACIÓN" DATE, 
	"LOCALIDAD" VARCHAR2(40 BYTE), 
	"DIVISIÓN" VARCHAR2(5 BYTE), 
	"ESTADIO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "LALIGA"."EQUIPO"."EQUIPO_ID" IS 'Clave Primaria';
   COMMENT ON COLUMN "LALIGA"."EQUIPO"."NOMBRE_EQUIPO" IS 'Denominación del equipo';
   COMMENT ON COLUMN "LALIGA"."EQUIPO"."FECHA_FUNDACIÓN" IS 'Fecha de la fundación del equipo';
   COMMENT ON COLUMN "LALIGA"."EQUIPO"."LOCALIDAD" IS 'Localidad a la que pertenece el equipo';
   COMMENT ON COLUMN "LALIGA"."EQUIPO"."DIVISIÓN" IS 'División en la que juega el equipo';
   COMMENT ON COLUMN "LALIGA"."EQUIPO"."ESTADIO_ID" IS 'Clave Ajena';
--------------------------------------------------------
--  DDL for Table ESTADIOS
--------------------------------------------------------

  CREATE TABLE "LALIGA"."ESTADIOS" 
   (	"ESTADIO_ID" NUMBER, 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"EMPLAZAMIENTO" VARCHAR2(40 BYTE), 
	"CAPACIDAD" NUMBER(6,0), 
	"FECHA_CONSTRUCCIÓN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "LALIGA"."ESTADIOS"."ESTADIO_ID" IS 'Clave Primaria';
   COMMENT ON COLUMN "LALIGA"."ESTADIOS"."NOMBRE" IS 'Nombre del estadio';
   COMMENT ON COLUMN "LALIGA"."ESTADIOS"."EMPLAZAMIENTO" IS 'Lugar de emplazamiento del estadio';
   COMMENT ON COLUMN "LALIGA"."ESTADIOS"."CAPACIDAD" IS 'Aforo del estadio';
   COMMENT ON COLUMN "LALIGA"."ESTADIOS"."FECHA_CONSTRUCCIÓN" IS 'Fecha de construcción del estadio';
--------------------------------------------------------
--  DDL for Table JUGADORES
--------------------------------------------------------

  CREATE TABLE "LALIGA"."JUGADORES" 
   (	"JUGADORES_ID" NUMBER, 
	"EQUIPO_ID" NUMBER, 
	"NOMBRE_JUGADOR" VARCHAR2(20 BYTE), 
	"APELLIDOS" VARCHAR2(40 BYTE), 
	"EDAD" NUMBER(2,0), 
	"DORSAL" NUMBER(2,0), 
	"DEMARCACIÓN" VARCHAR2(20 BYTE), 
	"SALARIO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "LALIGA"."JUGADORES"."JUGADORES_ID" IS 'Clave Primaria';
   COMMENT ON COLUMN "LALIGA"."JUGADORES"."EQUIPO_ID" IS 'Clave Ajena';
   COMMENT ON COLUMN "LALIGA"."JUGADORES"."NOMBRE_JUGADOR" IS 'Nombre del jugador';
   COMMENT ON COLUMN "LALIGA"."JUGADORES"."APELLIDOS" IS 'Apellidos del jugador';
   COMMENT ON COLUMN "LALIGA"."JUGADORES"."EDAD" IS 'Edad del jugador';
   COMMENT ON COLUMN "LALIGA"."JUGADORES"."DORSAL" IS 'Número del dorsal del jugador';
   COMMENT ON COLUMN "LALIGA"."JUGADORES"."DEMARCACIÓN" IS 'Posición de juego natural del  jugador';
   COMMENT ON COLUMN "LALIGA"."JUGADORES"."SALARIO" IS 'Salario mensual del jugador';
REM INSERTING into LALIGA."AFICIÓN"
SET DEFINE OFF;
Insert into LALIGA."AFICIÓN" ("AFICIÓN_ID",NOMBRE_GUERRA,EQUIPO_ID,ABONADOS) values ('1','BUKANEROS','1','9500');
REM INSERTING into LALIGA.AFICIONADOS_CONFLICTIVOS
SET DEFINE OFF;
REM INSERTING into LALIGA."CÁNTICOS"
SET DEFINE OFF;
Insert into LALIGA."CÁNTICOS" ("CÁNTICO_ID","AFICIÓN_ID","TÍTULO_CANCIÓN","FECHA_COMPOSICIÓN","LETRA_CANCIÓN") values ('1','1','LA VIDA PIRATA',null,'La vida pirata es la vida mejor:
sin estudiar,
sin trabajar...
¡cooooooooon la botella de ron!

Soy capitán
de un barco inglés
y en cada puerto tengo, tengo una mujer.
La rubia es
fenomenal
y la morena tampo, tampoco está mal.

Si alguna vez
me he de casar
con la del rayo, una, una y nada mas!!!!!!');
Insert into LALIGA."CÁNTICOS" ("CÁNTICO_ID","AFICIÓN_ID","TÍTULO_CANCIÓN","FECHA_COMPOSICIÓN","LETRA_CANCIÓN") values ('2','1','A LAS ARMAS!',null,'A las Armas,
A las Armas,
A las Armas,
A las Armas.

Somos de Vallekas
y vamos a ganar
vamos rayo

Lo lo lo loro lo,
lo loro lo lo lo,
lo lo lo lo loro
lo lo loro loro');
REM INSERTING into LALIGA.EQUIPO
SET DEFINE OFF;
Insert into LALIGA.EQUIPO (EQUIPO_ID,NOMBRE_EQUIPO,"FECHA_FUNDACIÓN",LOCALIDAD,"DIVISIÓN",ESTADIO_ID) values ('1','A.D. RAYO VALLECANO',to_date('01/01/24','DD/MM/RR'),'VALLEKAS','2A','1');
REM INSERTING into LALIGA.ESTADIOS
SET DEFINE OFF;
Insert into LALIGA.ESTADIOS (ESTADIO_ID,NOMBRE,EMPLAZAMIENTO,CAPACIDAD,"FECHA_CONSTRUCCIÓN") values ('1','ESTADIO MUNICIPAL DE VALLECAS','VALLEKAS','14000',to_date('01/01/24','DD/MM/RR'));
REM INSERTING into LALIGA.JUGADORES
SET DEFINE OFF;
Insert into LALIGA.JUGADORES (JUGADORES_ID,EQUIPO_ID,NOMBRE_JUGADOR,APELLIDOS,EDAD,DORSAL,"DEMARCACIÓN",SALARIO) values ('1','1','TOÑO','MARTÍNEZ','36','1','PORTERO','2500');
Insert into LALIGA.JUGADORES (JUGADORES_ID,EQUIPO_ID,NOMBRE_JUGADOR,APELLIDOS,EDAD,DORSAL,"DEMARCACIÓN",SALARIO) values ('2','1','ROBERTO','TRASHORRAS','35','10','CENTRO','3000');
Insert into LALIGA.JUGADORES (JUGADORES_ID,EQUIPO_ID,NOMBRE_JUGADOR,APELLIDOS,EDAD,DORSAL,"DEMARCACIÓN",SALARIO) values ('3','1','ÁLEX','MORENO','23','6','DELANTERO','1900');
Insert into LALIGA.JUGADORES (JUGADORES_ID,EQUIPO_ID,NOMBRE_JUGADOR,APELLIDOS,EDAD,DORSAL,"DEMARCACIÓN",SALARIO) values ('4','1','PATRICK','EBERT','29','20','CENTRO','2800');
REM INSERTING into LALIGA.VISTA_FUTBOL
SET DEFINE OFF;
Insert into LALIGA.VISTA_FUTBOL (NOMBRE_JUGADOR,APELLIDOS,SALARIO,NOMBRE_EQUIPO) values ('TOÑO','MARTÍNEZ','2500','A.D. RAYO VALLECANO');
Insert into LALIGA.VISTA_FUTBOL (NOMBRE_JUGADOR,APELLIDOS,SALARIO,NOMBRE_EQUIPO) values ('ROBERTO','TRASHORRAS','3000','A.D. RAYO VALLECANO');
Insert into LALIGA.VISTA_FUTBOL (NOMBRE_JUGADOR,APELLIDOS,SALARIO,NOMBRE_EQUIPO) values ('PATRICK','EBERT','2800','A.D. RAYO VALLECANO');
